# The Site Configuration

# Change to your full name.
# It will be displayed as the default author of the posts and the copyright owner in the Footer
name: weng
# change to your email address
email: example@doamin.com
repository: wengshenggui/wengshenggui.github.io

# Import the theme
theme:

# Only if your site type is GitHub Project sites and doesn't have a custom domain,
# change below value to '/projectname'.
baseurl: ''

# fill in the protocol & hostname for your site, e.g., 'https://username.github.io'
url: ''

# the HTML language tag › https://www.w3.org/International/questions/qa-choosing-language-tags
lang: en-US

# Change to your timezone › http://www.timezoneconverter.com/cgi-bin/findzone/findzone
timezone: Asia/Shanghai

# jekyll-seo-tag settings › https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
# --------------------------
# the main title
title: weng
# it will display as the sub-title
tagline:
# used by seo meta and the atom feed
description: >-
  A minimal, portfolio, sidebar,
  bootstrap Jekyll theme with responsive web design
  and focuses on text presentation.

# Prefer color scheme setting.
#
# Note: Keep empty will follow the system prefer color by default,
# and there will be a toggle to switch the theme between dark and light
# on the bottom left of the sidebar.
#
# Available options:
#
#     light  - Use the light color scheme
#     dark   - Use the dark color scheme
#
theme_mode:   # [light|dark]

# The CDN endpoint for images.
# Notice that once it is assigned, the CDN url
# will be added to all image (site avatar & posts' images) paths starting with '/'
#
# e.g. 'https://cdn.com'
img_cdn: ''

# the avatar on sidebar, support local or CORS resources
avatar: https://avatars.githubusercontent.com/u/28017224?v=4

# boolean type, the global switch for ToC in posts.
toc: true

paginate: 10

# ------------ The following options are not recommended to be modified ------------------

kramdown:
  syntax_highlighter: rouge
  # Rouge Options › https://github.com/jneen/rouge#full-options
  syntax_highlighter_opts:
    css_class: highlight
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    # jekyll 4.0
    sort_by: order


defaults:
  -
    scope:
      # An empty string here means all files in the project
      path: ''
      type: posts
    values:
      layout: post
      # Enable comments in posts.
      comments: true
      # Display TOC column in posts.
      toc: true
      # DO NOT modify the following parameter unless you are confident enough
      # to update the code of all other post links in this project.
      permalink: /posts/:title/
  -
    scope:
      path: _drafts
    values:
      comments: false
  -
    scope:
      path: ''
      # see `site.collections`
      type: tabs
    values:
      layout: page
      permalink: /:title/
      # Hide title in mobile screens.
      dynamic_title: true

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - vendor
  - '*.gem'
  - '*.gemspec'
  - tools
  - docs
  - README.md
  - LICENSE
  - gulpfile.js
  - node_modules
  - package.json
  - Gemfile

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/

port: 4040
